package com.rendox.grocerygenius.ui.theme.color_schemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val PinkLightColorScheme = lightColorScheme(
    primary = Color(0xFF9C4147),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDADA),
    onPrimaryContainer = Color(0xFF40000B),
    secondary = Color(0xFF765657),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDADA),
    onSecondaryContainer = Color(0xFF2C1516),
    tertiary = Color(0xFF76592F),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDDB0),
    onTertiaryContainer = Color(0xFF291800),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color(0xFFFFFFFF),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201A1A),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF201A1A),
    surfaceVariant = Color(0xFFF4DDDD),
    onSurfaceVariant = Color(0xFF524343),
    outline = Color(0xFF857373),
    inverseOnSurface = Color(0xFFFBEEED),
    inverseSurface = Color(0xFF362F2F),
    inversePrimary = Color(0xFFFFB3B5),
    surfaceTint = Color(0xFF9C4147),
    outlineVariant = Color(0xFFD7C1C1),
    scrim = Color(0xFF000000),
)

val PinkDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFFB3B5),
    onPrimary = Color(0xFF5F121D),
    primaryContainer = Color(0xFF7E2931),
    onPrimaryContainer = Color(0xFFFFDADA),
    secondary = Color(0xFFE6BDBD),
    onSecondary = Color(0xFF44292A),
    secondaryContainer = Color(0xFF5D3F40),
    onSecondaryContainer = Color(0xFFFFDADA),
    tertiary = Color(0xFFE6C18D),
    onTertiary = Color(0xFF422C05),
    tertiaryContainer = Color(0xFF5B421A),
    onTertiaryContainer = Color(0xFFFFDDB0),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF201A1A),
    onBackground = Color(0xFFECE0DF),
    surface = Color(0xFF201A1A),
    onSurface = Color(0xFFECE0DF),
    surfaceVariant = Color(0xFF524343),
    onSurfaceVariant = Color(0xFFD7C1C1),
    outline = Color(0xFF9F8C8C),
    inverseOnSurface = Color(0xFF201A1A),
    inverseSurface = Color(0xFFECE0DF),
    inversePrimary = Color(0xFF9C4147),
    surfaceTint = Color(0xFFFFB3B5),
    outlineVariant = Color(0xFF524343),
    scrim = Color(0xFF000000),
)
