package com.rendox.grocerygenius.ui.theme.color_schemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val PurpleLightColorScheme = lightColorScheme(
    primary = Color(0xFF5B53A8),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE4DFFF),
    onPrimaryContainer = Color(0xFF160362),
    secondary = Color(0xFF5E5C71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE4DFF9),
    onSecondaryContainer = Color(0xFF1B192C),
    tertiary = Color(0xFF7B5266),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD8E8),
    onTertiaryContainer = Color(0xFF2F1122),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color(0xFFFFFFFF),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFE5E1EC),
    onSurfaceVariant = Color(0xFF47464F),
    outline = Color(0xFF787680),
    inverseOnSurface = Color(0xFFF4EFF4),
    inverseSurface = Color(0xFF313034),
    inversePrimary = Color(0xFFC6C0FF),
    surfaceTint = Color(0xFF5B53A8),
    outlineVariant = Color(0xFFC8C5D0),
    scrim = Color(0xFF000000),
)

val PurpleDarkColorScheme = darkColorScheme(
    primary = Color(0xFFC6C0FF),
    onPrimary = Color(0xFF2C2276),
    primaryContainer = Color(0xFF433B8E),
    onPrimaryContainer = Color(0xFFE4DFFF),
    secondary = Color(0xFFC8C3DC),
    onSecondary = Color(0xFF302E41),
    secondaryContainer = Color(0xFF474459),
    onSecondaryContainer = Color(0xFFE4DFF9),
    tertiary = Color(0xFFEBB8CF),
    onTertiary = Color(0xFF482537),
    tertiaryContainer = Color(0xFF613B4E),
    onTertiaryContainer = Color(0xFFFFD8E8),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1C1B1F),
    onBackground = Color(0xFFE5E1E6),
    surface = Color(0xFF1C1B1F),
    onSurface = Color(0xFFE5E1E6),
    surfaceVariant = Color(0xFF47464F),
    onSurfaceVariant = Color(0xFFC8C5D0),
    outline = Color(0xFF928F99),
    inverseOnSurface = Color(0xFF1C1B1F),
    inverseSurface = Color(0xFFE5E1E6),
    inversePrimary = Color(0xFF5B53A8),
    surfaceTint = Color(0xFFC6C0FF),
    outlineVariant = Color(0xFF47464F),
    scrim = Color(0xFF000000),
)